[pytest]

addopts =
    --strict-markers
    --html=report.html
;    --headed
;    --browser chromium
;    --start-maximized


markers =
    positive: for positive tests
    negative: for negative tests
    triangle: to check triangle functionality
    regression: to run regression tests
    smoke: to run smoke tests
    prime: to check prime functionality
    qaauto_api: api tests for aq_auto endpoints
    ui: for ui saucedemo tests
    swapi: for swapi tests
; python_files = *_automation.py
; python_functions = tc_*